name: AutoDL
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *' 
  
jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Install RClone
        run: |
              curl https://rclone.org/install.sh | sudo bash
      - name: Pyrogram
        run: |
          pip install  pyrofork && pip install tgcrypto && pip install vcsi && pip install psycopg2 && pip install fpdf && pip install pillow && pip install gofile2
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Cd Into Repo
        run: |
          cd ${{ github.workspace }}
      - name: Downloading config file
        run: |
          wget -qq ${{ secrets.RCLONE }} -O rclone.conf
      - name: Downloading links
        run : |
          wget https://gist.github.com/BlackFoxy616/129bec38c78a07355588b602ca2c5152/raw/links.txt && wget https://gist.github.com/BlackFoxy616/cb76be7842c810328ac99cee2f070306/raw/dled.txt && wget https://gist.github.com/BlackFoxy616/b29d70dd199f557d7516f33e7011e8cb/raw/dl.txt
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
        with:
          with-ffmpeg: true
      - name: Running the Script 
        run : |
          python update.py
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 2d56ab7f0678654ed0fdcad9325832f4
          file_path: autodl.txt
          file_type: text
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 129bec38c78a07355588b602ca2c5152
          file_path: links.txt
          file_type: text
